[package]
name = "spdm"
version = "0.1.0"
edition = "2021"
authors = ["lxyboy <lxyboy@hotmail.com>"]
license = "Apache-2.0 OR MIT"

[dependencies]
ringbuffer = { version = "0.15.0", default-features = false }

[dev-dependencies]
format_no_std = "1.2.0"

[profile.release]
opt-level = 3
